# Generated by Django 4.0.2 on 2022-02-02 19:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='plantModule',
        ),
    ]
