# Generated by Django 4.0.2 on 2022-02-02 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_account_accounts'),
    ]

    operations = [
        migrations.AddField(
            model_name='accounts',
            name='is_staff',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='accounts',
            name='username',
            field=models.CharField(max_length=30, null=True, unique=True),
        ),
    ]
