# Generated by Django 4.0.2 on 2022-02-05 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_accounts_is_staff_accounts_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accounts',
            name='is_superuser',
        ),
        migrations.AlterField(
            model_name='accounts',
            name='email',
            field=models.EmailField(max_length=255, unique=True, verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='accounts',
            name='username',
            field=models.CharField(default='username', max_length=30, unique=True),
        ),
    ]
