# Generated by Django 4.1.dev20220302192339 on 2022-04-04 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("modules", "0003_alter_plantmodule_name_alter_plantmodule_plants"),
    ]

    operations = [
        migrations.AlterField(
            model_name="plantmodule",
            name="name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="plantmodule",
            name="plants",
            field=models.TextField(blank=True, default="plants", max_length=5000),
            preserve_default=False,
        ),
    ]
